### ISSUE TITLE
python-slugify [required: ==1.1.4] in NVD3

### ISSUE THREAD

**Issue by lggwettmann** [PetrDlouhy/django-admin-charts#14]
Hey guys,

the dependency with django-NVD3 raises a pipenv error cause django-nvd3 strictly asks for python-slugify==1.1.4

How can I solve this? I already posted on their issues board, but since they haven't had any update in the last 2 years, I don't expect much out of that.

**Comment by PetrDlouhy** [comment]
Hi @lggwettmann,

I install with `develop` branch of `python-nvd3` (`pip install git+https://github.com/areski/python-nvd3@develop#egg=python-nvd3`).
You would have to poke @areski to release new version at https://github.com/areski/python-nvd3 to get this installed properly.

**Comment by lggwettmann** [comment]
Ah thanks! I did that.
