### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by Mirakul1** [PetrDlouhy/django-admin-charts#17]
I am trying to install the application using `pip install django-admin-charts`, but I keep getting this error 
`ERROR: Could not install packages due to an EnvironmentError: [Errno 22] Invalid argument: 'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-fzl00olu\\django-admin-charts\\admin_tools_stats/:qa'`

I am using Python 3.7.5,  on Windows 10.
From my research online, the `/:qa` at the end of the path could be the problem. 
Please how do I resolve this??

Below is the complete traceback:

`Collecting django-admin-charts
  Using cached https://files.pythonhosted.org/packages/a6/5f/e0d45a766ebc7f8ba0702b45b930175a78efb7eab9317a7577e6986af0a4/django-admin-charts-0.20.0.tar.gz
ERROR: Could not install packages due to an EnvironmentError: [Errno 22] Invalid argument: 'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-fzl00olu\\django-admin-charts\\admin_tools_stats/:qa'`

**Comment by PetrDlouhy** [comment]
@Mirakul1 Seems like the `:qa` file got accidentally into the release. That file name is OK on Linux, but not allowed on Windows, that is why I did not notice.
Now it should be fixed.

**Comment by Mirakul1** [comment]
Okay, thanks. I will check it out
