### ISSUE TITLE
Analytics view buttons not working in FF

### ISSUE THREAD

**Issue by wanaryytel** [PetrDlouhy/django-admin-charts#22]
The buttons in the new analytics view work in Google Chrome but in Firefox they take you to a new page that just shows this text `[object Object]`.

**Comment by PetrDlouhy** [comment]
Hi @wanaryytel, I tried analytics on Firefox `80.0.1` and everything works fine. Can you please provide more information about this issue? Like Firefox version, debug console output (both dev tools in Firefox and Django).

**Comment by PetrDlouhy** [comment]
@wanaryytel Now I bumped to that error, so ignore the previous message.

**Comment by PetrDlouhy** [comment]
@wanaryytel Can you please try newset `master` if it is fixed for you?

**Comment by wanaryytel** [comment]
@PetrDlouhy Yes, that fixed it! Thanks!
