### ISSUE TITLE
psycopg2.ProgrammingError: can't adapt type 'SimpleLazyObject'

### ISSUE THREAD

**Issue by alexey74** [PetrDlouhy/django-admin-charts#23]
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
web_1       |     response = get_response(request)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
web_1       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 73, in view
web_1       |     return self.dispatch(request, *args, **kwargs)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
web_1       |     return bound_method(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
web_1       |     return view_func(request, *args, **kwargs)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 101, in dispatch
web_1       |     return handler(request, *args, **kwargs)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 163, in get
web_1       |     context = self.get_context_data(**context_kwargs)
web_1       |   File "/usr/local/lib/python3.8/site-packages/admin_tools_stats/views.py", line 58, in get_context_data
web_1       |     dashboard_stats = DashboardStats.objects.get(graph_key=graph_key)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
web_1       |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 425, in get
web_1       |     num = len(clone)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 269, in __len__
web_1       |     self._fetch_all()
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1303, in _fetch_all
web_1       |     self._result_cache = list(self._iterable_class(self))
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
web_1       |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
web_1       |     cursor.execute(sql, params)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
web_1       |     return super().execute(sql, params)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
web_1       |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
web_1       |     return executor(sql, params, many, context)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1       |     return self.cursor.execute(sql, params)
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
web_1       |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1       |     return self.cursor.execute(sql, params)
web_1       | django.db.utils.ProgrammingError: can't adapt type 'SimpleLazyObject'

**Comment by PetrDlouhy** [comment]
@alexey74 Please give detailed description of your case (like your models used `DashboardStats` settings, which view does throw that error, local variables in the `/usr/local/lib/python3.8/site-packages/django/db/models/manager.py` call, etc.).
My first guess is that you have some kind of misconfiguration - probably the `User` model is given from `get_user()` function as `SimpleLazyObject` and should be evaluated.

**Comment by PetrDlouhy** [comment]
It was probably caused by the JSONfield. From Django 3.1 it has native implementation, so I am trying to switch to that in branch @jsonfield. @alexey74  Can you please test that branch?

**Comment by alexey74** [comment]
In fact, the problem can be fixed by converting some arguments in `get_context_data()` to `str`, and `graph_key` may be the only one required:

```
diff --git a/admin_tools_stats/views.py b/admin_tools_stats/views.py
index ac7c521..52cc5cd 100644
--- a/admin_tools_stats/views.py
+++ b/admin_tools_stats/views.py
@@ -47,18 +47,27 @@
 
     def get_context_data(self, *args, interval=None, graph_key=None, **kwargs):
         context = super().get_context_data(*args, **kwargs)
-        interval = self.request.GET.get('select_box_interval', interval)
-        context['chart_type'] = self.request.GET.get('select_box_chart_type', interval)
+        interval = str(self.request.GET.get('select_box_interval', interval))
+        context['chart_type'] = str(
+            self.request.GET.get('select_box_chart_type', interval)
+        )
+        graph_key = str(graph_key)
```

**Comment by cy** [comment]
@PetrDlouhy, I tried @alexey74's suggestion to cast interval, chart_type and graph_key to str in my project. It *does* work on the `jsonfield` branch, but does not work on master. It does look like the `jsonfield` branch is merged to master, so did something else change on master since `jsonfield` branch was merged?

**Comment by PetrDlouhy** [comment]
I am really confused what is happening here, and the @alexey74's code doesn't seem to me like proper fix of the problem. At leas I am not able to write proper test for this.

I am probably lacking some essential information:

- What is the URL, where this error occurs?
- Why is there SimpleLazyObject on the `graph_key` parameter, if the parameter should be given by the view call?
- On what Django versions does this occur?

**Comment by cy** [comment]
- the error occurs when loading the `/admin` django admin front page where the graphs are shown
- I'm not well versed enough in the workings of this lib to answer this question
- it occurs on Django 3.1.0

**Comment by PetrDlouhy** [comment]
@cy When you load the `/admin` page, how you get the error? Do you get the JavaScript alert popup message with the error?

The `django-admin-charts` library makes AJAX calls in the background, so I would need the URL of that call. Please use development tools in your browser and copy the last call URLs from the network panel including all query parameters. The URL should start with `/chart_data`.

Also, I might need to know more about settings of the failing chart. Screenshot of the DashboardStats settings admin page would be very helpful.

**Comment by PetrDlouhy** [comment]
I probably found the problem, which is in fact caused by Django itself: https://code.djangoproject.com/ticket/31877

Please try to upgrade Django 3.1 to at least 3.1.1. In fact you should always use the highest patch number to get all security fixes.

**Comment by cy** [comment]
@PetrDlouhy thank you for figuring it out! Yes upgrading to 3.1.1 fixed it 👍
