### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'year' when running demo project

### ISSUE THREAD

**Issue by WhiteRose7-pretty** [PetrDlouhy/django-admin-charts#24]
Hello @PetrDlouhy
I am running demo project.
but I can't see graph and getting bug.
Thank you in advance for any help.
Django:2.2, Python:3.7 and 3.8
 
AttributeError: 'NoneType' object has no attribute 'year' when running demo project

![image](https://user-images.githubusercontent.com/53968816/96333041-2f546480-109a-11eb-9fd8-14840e91d5bf.png)

I am getting this error in this links

Request Method: | GET
-- | --
http://localhost:9015/admin_tools_stats/chart_data/user_graph/?csrfmiddlewaretoken=zL0VEagK1lHnSbSL5o58a979NO39gUGn8ZV5U0rGEz6lepSxvm0iDGkHwKHZ9h9z&select_box_dynamic_1=&graph_key=user_graph&select_box_multiple_series=&select_box_interval=days&time_since=2020-09-16&time_until=2020-10-17&select_box_chart_type=stackedAreaChart&_=1602925104781
2.2
AttributeError
'NoneType' object has no attribute 'year'
F:\Python\Bot\django-admin-charts\demoproject\venv\lib\site-packages\admin_tools_stats\views.py in <lambda>, line 82
F:\Python\Bot\django-admin-charts\demoproject\venv\Scripts\python.exe
3.8.4
['F:\\Python\\Bot\\django-admin-charts\\demoproject',  'C:\\Python38\\python38.zip',  'C:\\Python38\\DLLs',  'C:\\Python38\\lib',  'C:\\Python38',  'F:\\Python\\Bot\\django-admin-charts\\demoproject\\venv',  'F:\\Python\\Bot\\django-admin-charts\\demoproject\\venv\\lib\\site-packages',  'C:\\Users\\cholp\\AppData\\Roaming\\Python\\Python38\\site-packages',  'C:\\Python38\\lib\\site-packages']
Sat, 17 Oct 2020 04:02:34 -0500

**Comment by PetrDlouhy** [comment]
Hi @WhiteRose7-pretty I tried it, and successfully reproduced the issue. I realised, that this issue is present only in Django 3.1, but not in 3.0, and the underlying error is probably the same as in #23. I will try to find, what changed in the newest Django, in the meantime, you can test with the older version.

**Comment by PetrDlouhy** [comment]
It was probably caused by the JSONfield. From Django 3.1 it has native implementation, so I am trying to switch to that in branch @jsonfield. @WhiteRose7-pretty Can you please test that branch?

**Comment by WhiteRose7-pretty** [comment]
Hi, @PetrDlouhy 
code part making bug
`        for date in sorted(series.keys(), key=lambda d: datetime(d.year, d.month, d.day, getattr(d, 'hour', 0))):
            xdata.append(int(time.mktime(date.timetuple()) * 1000))
            for key, value in series[date].items():
                if key not in serie_i_map:
                    serie_i_map[key] = len(serie_i_map)
                y_key = 'y%i' % serie_i_map[key]
                if y_key not in ydata_serie:
                    ydata_serie[y_key] = []
                    names['name%i' % serie_i_map[key]] = str(choices[key][1] if key in choices else key)
                ydata_serie[y_key].append(value)
`
I print series.
`{None: {'': 3}, datetime.datetime(2020, 10, 15, 0, 0, tzinfo=<DstTzInfo 'America/Chicago' CDT-1 day, 19:00:00 DST>): OrderedDict([('', 0)]), datetime.datetime(2020, 10, 16, 0, 0, tzinfo=<DstTzInfo 'America/Chicago' CDT-1 day, 19:00:00 DST>): OrderedDict([('', 0)]),
 datetime.datetime(2020, 10, 17, 0, 0, tzinfo=<DstTzInfo 'America/Chicago' CDT-1 day, 19:00:00 DST>): OrderedDict([('', 0)]), datetime.datetime(2020, 10, 18, 0, 0, tzinfo=<DstTzInfo 'America/Chicago' CDT-1 day, 19:00:00 DST>): OrderedDict([('', 0)])}
`
First element None: {'': 3} is making bug.
Is this needed data or inserted data as bug?

**Comment by WhiteRose7-pretty** [comment]
But result always zero.
![image](https://user-images.githubusercontent.com/53968816/96388426-45b60980-11db-11eb-97dc-174964ba06c1.png)
I changed user's last login data and register date. and I have added new user.
but alyays 0.

**Comment by PetrDlouhy** [comment]
What is your database and it's version?
Can you print output of `models -> get_time_series()` (the `qs.all()`)?

**Comment by WhiteRose7-pretty** [comment]
At the moment, I am using sqlite3 and postgreSQL will be used in the future.
```
series = dashboard_stats.get_multi_time_series(self.request.GET, time_since, time_until, interval, self.request)
            print(series)

{None: {'': 10}, datetime.datetime(2020, 10, 13, 0, 0, tzinfo=<DstTzInfo 'America/Chicago' CDT-1 day, 19:00:00 DST>): OrderedDict([('', 0)]), datetime.datetime(2020, 10, 14, 0, 0, tzinfo=<DstTzInfo 'America/Chicago' CDT-1 day, 19:00:00 DST>): OrderedDict([('', 0)])
, datetime.datetime(2020, 10, 15, 0, 0, tzinfo=<DstTzInfo 'America/Chicago' CDT-1 day, 19:00:00 DST>): OrderedDict([('', 0)]), datetime.datetime(2020, 10, 16, 0, 0, tzinfo=<DstTzInfo 'America/Chicago' CDT-1 day, 19:00:00 DST>): OrderedDict([('', 0)]), datetime.date
time(2020, 10, 17, 0, 0, tzinfo=<DstTzInfo 'America/Chicago' CDT-1 day, 19:00:00 DST>): OrderedDict([('', 0)]), datetime.datetime(2020, 10, 18, 0, 0, tzinfo=<DstTzInfo 'America/Chicago' CDT-1 day, 19:00:00 DST>): OrderedDict([('', 0)]), datetime.datetime(2020, 10,
19, 0, 0, tzinfo=<DstTzInfo 'America/Chicago' CDT-1 day, 19:00:00 DST>): OrderedDict([('', 0)])}
```

**Comment by PetrDlouhy** [comment]
@WhiteRose7-pretty I didn't test on any other database than PostgreSQL,and I think, the date aggregation can vary between databases. So please try the PostgreSQL. PRs with the tests and support in for other databases are welcome. I will at least write some note to the README about that.

**Comment by WhiteRose7-pretty** [comment]
Thank you, I solve the issue with PostgreSQL.
