### ISSUE TITLE
Reverse for 'admin-charts' not found. 'admin-charts' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by WhiteRose7-pretty** [PetrDlouhy/django-admin-charts#28]
Hi, @PetrDlouhy 
Now after I install django-admin-charts package, I am getting this error.
python: 3.6.9
database: postgresql
django: 2.2
django-admin-charts==0.24.1
and here is all trace back.
https://dpaste.com/EH7F4YLT3
Thank you in advance

**Comment by PetrDlouhy** [comment]
The issue is closed, @WhiteRose7-pretty did you solve it?

**Comment by WhiteRose7-pretty** [comment]
@PetrDlouhy yes, I solved
there were some mistake in urls.py.
I didn't add this path to urls
path('admin_tools_stats/', include('admin_tools_stats.urls')),
Thanks @PetrDlouhy
