### ISSUE TITLE
Users who are not super users, but can still access the admin, i.e staff level users, cannot view the charts

### ISSUE THREAD

**Issue by milin** [PetrDlouhy/django-admin-charts#32]
Looks like they get redirected too many times, at the http://localhost:8001/admin_tools_stats/chart_data/<graph_key> view layer.

**Comment by PetrDlouhy** [comment]
@milin There is change in the `master` branch now, with which you can manage non-superusers that by permissions.
Also there is  `frontend_users` branch, which takes this many steps further and allows to set up charts even for frontend users.

**Comment by milind-shakya-sp** [comment]
Good to know. Is there a pip version that this change is associated with

**Comment by PetrDlouhy** [comment]
Not yet. I would like release the frontend users changes, but I will need to do more testing.

**Comment by milin** [comment]
Closing the issue since I can use the master branch for now, and this is fixed in the master branch

**Comment by PetrDlouhy** [comment]
@millin I released version `0.25.0` with the permissions fix included and also with the frontend users feature.
Please test and report if you find any problem.

**Comment by millin** [comment]
@PetrDlouhy It seems you made a mistake tagging me :smile:

**Comment by PetrDlouhy** [comment]
Ah, sorry. Should be @milind-shakya-sp

**Comment by milin** [comment]
@PetrDlouhy Thanks 👍
