### ISSUE TITLE
Simple examples needed: how to show a graph of newly registered users 

### ISSUE THREAD

**Issue by pavitrakumar78** [PetrDlouhy/django-admin-charts#37]
Hi,

Thanks for building this library!

I'm so far able to get a graph where I'm able to see the total count of users per day/week, but how can I get a growth graph?

something like: 

```
select date_joined, count(*) over (order by date_joined) from auth_user
```

Is this possible with the current features?

**Comment by PetrDlouhy** [comment]
Hi @pavitrakumar78,

if you mean graph of how many users has registrated up till certain day in the graph, then probably no.
It is not possible to do directly in this library.

You can of course count such field in your database or achieve that by matreialized DB views, or something like that, but that is not very practical and easy.

PRs with this functionality are welcome.

**Comment by pavitrakumar78** [comment]
Thank you for your response! I understand. 

I will close this issue for now.
