### ISSUE TITLE
Blank Analytics Page

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [PetrDlouhy/django-admin-charts#42]
I've installed the `django-admin-charts` by following the steps in this repo.

After installation and configuring necessary things,  when I open [http://localhost:8000/admin_tools_stats/analytics/](http://localhost:8000/admin_tools_stats/analytics/) I got a blank page with just the home button.

![Admin tools stats Page](https://user-images.githubusercontent.com/66238621/182179395-a82cf144-1c99-4a3a-82b2-c991ae4df329.png)

- [x] Placed apps in `INSTALLED_APPS` in the right order as mentioned.

**Comment by PetrDlouhy** [comment]
@DilLip-Chowdary-Codes Did you add `Dashboard stats` objects as it was written in the last paragraph of `Basic setup for django-admin`?
The charts should appear also on the bottom of admin index page, but they need to be configured for every model separately.

**Comment by PetrDlouhy** [comment]
@DilLip-Chowdary-Codes I have created new version `1.1.0` which clearly shows information with link where to create new stats.
Hope this will help future users.

**Comment by DilLip-Chowdary-Codes** [comment]
Actually i'm using custom package for customise Model Admins, adding `admin_tools_stats.DashboardStats` in it resolved the issue.
