### ISSUE TITLE
Add missing migration 0019_alter_cachedvalue_id_alter_criteriatostatsm2m_id_and_more

### ISSUE THREAD

**Issue by seravb** [PetrDlouhy/django-admin-charts#49]
Could you upload the last missing migration "0019_alter_cachedvalue_id_alter_criteriatostatsm2m_id_and_more" please? And could you update the README with all the possible instructions on how to start with the package to contribute with you? Thanks a lot.

**Comment by PetrDlouhy** [comment]
@seravb The migrations are now complete and checked for every commit. Maybe there is something dependent on your configuration - e.g. are you using `DEFAULT_AUTO_FIELD=BigAutoField`? Anyway - it would help if you could post content of your migration file generated by `makemigrations`.

If that is the case, I am not sure, how to solve this problem. Maybe we can start using BigAutoFields on app level. Or make the migrations dependent on the global settings (but I am not sure how to make it correctly).

What exactly are you missing in the README file? There are sections `development` and `contributing` in the README.
Do you want to start contributing? Then you can make pull request here on GitHub.

**Comment by PetrDlouhy** [comment]
I am closing this issue due to lack of information.

@seravb Please feel free to reopen with answers to my questions.
