### ISSUE TITLE
No plots if graph identified has dashes

### ISSUE THREAD

**Issue by makseq** [PetrDlouhy/django-admin-charts#50]
![image](https://user-images.githubusercontent.com/501780/204689168-a4acf05f-733f-4b26-b6db-62bab10b6d98.png)

![image](https://user-images.githubusercontent.com/501780/204689275-3a2d6619-66e4-45c4-8d7e-446233054202.png)

**Comment by PetrDlouhy** [comment]
@makseq Thank you for noticing this. I added a validator to not allow dashes and also capital letters in Graph identifier in #51.
I found it difficult to make this working with dash, because the normalization is done in [django-nvd3](https://pypi.org/project/django-nvd3/0.0.4/).

**Comment by makseq** [comment]
Thank you!
