### ISSUE TITLE
hardcoded urls -> reverse urls

### ISSUE THREAD

**Issue by alvarantson** [PetrDlouhy/django-admin-charts#53]
Some urls seem to be hardcoded!
Should be rewritten to reverse url-s because for an example if you change the main route for all django routes to asd.com/xyz/.... then the app breaks!

PS: might have even more routes hardcoded, not only those shown on the picture!

![image](https://user-images.githubusercontent.com/47379716/212668263-8e292c1c-3501-4445-aa74-7e550fb318b7.png)

**Comment by PetrDlouhy** [comment]
@alvarantson I found the only occurence in admin_charts.js and made PR for this: #54 
Please, check it and test it.
Also, if you know better solution how to overcome the parameter unknown at rendering time than creating blank record in `urls.py`, please tell.

**Comment by PetrDlouhy** [comment]
@alvarantson I have released version 1.3.0 where this issue should be fixed. Please check.
