### ISSUE TITLE
'No charts available, please configure them' appear. What should I do?

### ISSUE THREAD

**Issue by tnajun** [PetrDlouhy/django-admin-charts#62]
'No charts available, please configure them' appear on the left of dashboard stats. What should I do to turn off the comment? Please note Jazzmin is installed.

![スクリーンショット 2023-06-02 112000](https://github.com/PetrDlouhy/django-admin-charts/assets/15953917/12af0fef-e96f-4250-a455-571aa44d6a04)

**Comment by swills1** [comment]
@tnajun, I'm absolutely brand new to this package / app. I am reading through it allto see it it will fit my project.

If you search the code, you can see that message most likely comes from `chart_containers.html`.

It uses a for and inside that for an `{% empty %}`.  Which means, if the array is empty, it will display `No charts available, please <a href="{% url 'admin:admin_tools_stats_dashboardstats_changelist' %}">configure them</a>`.

See here for more details and an example.
https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#for-empty

Have you clicked on the link? If so, where does it take you and what options does it give you to "configure"? 

That is where I would start. Then provide more detail if possible.

**Comment by PetrDlouhy** [comment]
Is it possible, that this is might be solved by #72?

**Comment by santiago1114** [comment]
Yes, it doesn't appears...

![image](https://github.com/PetrDlouhy/django-admin-charts/assets/55591455/954fd982-575f-4252-9250-78568d14a43c)

![image](https://github.com/PetrDlouhy/django-admin-charts/assets/55591455/5e310058-d977-44d6-a870-01a5a6bc9b44)

**Comment by PetrDlouhy** [comment]
Closing this since it appears to be solved.
