### ISSUE TITLE
No migrations to apply.

### ISSUE THREAD

**Issue by mvalenzisi** [PetrDlouhy/django-admin-charts#66]
I followed the installation instructions but I don't get any migration:
```
Operations to perform:
  Apply all migrations: admin, admin_tools_stats, api, auth, authtoken, blacklist, contenttypes, reversion, sessions, social_django
Running migrations:
  No migrations to apply.
```

Python: 3.10.13
Django: 4.2.6
django-admin-charts: 1.3.0

Any help is appreciated.

**Comment by PetrDlouhy** [comment]
I don't very much understand what is the problem here.
Seems like the DB is already migrated.

**Comment by mvalenzisi** [comment]
I should have mentioned that the application throws this error:
```
relation "dashboard_stats" does not exist
LINE 1: ...ated_date", "dashboard_stats"."updated_date" FROM "dashboard...
```

**Comment by PetrDlouhy** [comment]
Yeah, that looks like the migration didn't go through properly.
But also is probably not fault of `django-admin-chart`.

Didn't you run the migration first time with `--fake` or something like that? If so you can use `--fake` to change to previous migration and then run proper migrations.

**Comment by mvalenzisi** [comment]
It's an existing Django project where I'm trying to add `django-admin-chart`,
I'm not sure that `--fake` is what I need to use in this case.

**Comment by PetrDlouhy** [comment]
You can change migration state without actually running the migrations by using `--fake` parameter on the `migrate` command.

I am closing this issue as it is not issue/bug in `django-admin-charts`.
