### ISSUE TITLE
ValueError at /admin/admin_tools_stats/dashboardstats/add/

### ISSUE THREAD

**Issue by Antipire** [PetrDlouhy/django-admin-charts#70]
I freshly installed **django-admin-charts** and tried to add new dashboard chart, and got the error that mentioned in the title. To install I followed provided instruction in [readme.rst](https://github.com/PetrDlouhy/django-admin-charts/blob/master/README.rst)

My db is sqlite

More detailed error:
ValueError at /admin/admin_tools_stats/dashboardstats/add/
Model instances passed to related filters must be saved.
![image](https://github.com/PetrDlouhy/django-admin-charts/assets/22982005/9cc8c5e9-8a17-4efa-b0ae-9a06a42fcdd4)

I haven't modified admin.py file, only to register my models.

Installed pip packages
- asgiref                 3.7.2
- datetime-truncate       1.1.1
- Django                  5.0.1
- django-admin-charts     1.3.0
- django-bower            5.2.0
- django-chartjs          2.3.0
- django-crispy-forms     2.1
- django-matplotlib       0.1
- django-memoize          2.3.1
- django-multiselectfield 0.1.12
- django-nvd3             0.9.7
- Jinja2                  3.1.3
- MarkupSafe              2.1.3
- pip                     23.2.1
- python-dateutil         2.8.2
- python-nvd3             0.14.2
- python-slugify          1.1.4
- setuptools              68.2.0
- six                     1.16.0
- sqlparse                0.4.4
- typing_extensions       4.9.0
- tzdata                  2023.4
- Unidecode               1.3.8
- wheel                   0.41.2

**Comment by Antipire** [comment]
Forgot to mention: I can freely add _Cached values_ and _Dashboard stats_ criteria but not the _Dashboard stats_.

**Comment by PetrDlouhy** [comment]
This is useless without full stacktrace.

**Comment by Antipire** [comment]
@PetrDlouhy Thanks for your reply. Perhaps the problem is in sqlite. I looked at my database schema and didn't find any new tables for django-admin-charts that are in other tutorials.

**Comment by Antipire** [comment]
Closed for further investigations and developing

**Comment by aadith00** [comment]
@Antipire I am using Postgres but still encountering the same error. Can you please tell me how did you solve this error?

**Comment by Antipire** [comment]
@aadith00 Make sure you ran migrations. If you did, check the new tables in your database.

**Comment by aadith00** [comment]
Yeah I ran migrations and the table is also defined fine but still facing
the same issue.

**Comment by Antipire** [comment]
@aadith00 I'm sorry to hear that you still facing the problem. I couldn't help you because I gave up on solving the problem. I needed Django-admin-charts mainly for educational purposes to create charts, but in the end I switched to ChartJS.

**Comment by aadith00** [comment]
No problem, I understand.
Thank you
